version: '3.9'

services:

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345L
      POSTGRES_USER: MainUser
      POSTGRES_DB: L0
    ports:
      - "5433:5432"

  nats:
    image: nats-streaming:latest
    container_name: nats
    restart: always
    ports:
      - "4222:4222"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"